### ISSUE TITLE
What is an 'account' and what is a 'user'

### ISSUE THREAD

**Issue by felipe1982** [camptocamp/puppet-accounts#37]
What is the difference between an _account_ and a _user_ from the perspective of this module?

How can I just use hiera _only_ to create/destroy users? I don't want to edit .pp files when I want new users created. 

Please help as I'm unable to get it working, but I think I can with a bit of assistance.

**Comment by johnzimm** [comment]
A user is essentially just the "username" on the system.  An "account" in this module includes all the other things associated with the user when created (e.g. home directory, uid, ssh keys, groups, password, etc...).

You can create and destroy users by setting the ensure parameter in your hierahash.  Take a look at the options here: https://github.com/camptocamp/puppet-accounts/blob/master/manifests/account.pp

Be default ensure => present.  But if you set it to ensure => absent puppet will make sure the account does not exist.

You can set it up to so that all users are specified in hiera (and you should).

The README walks through this and reading the manifests help to understand what is happening.

Are you getting hung up on a specific part of it?  Exactly how you implement will depend on what you're trying to accomplish in your infrastructure.
